### ISSUE TITLE
Crash during startup: NullPointerException: Rendering ingredient

### ISSUE THREAD

**Issue by Lothrazar** [CyclopsMC/FluidConverters#37]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.5.1.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-69.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 8/4/17 8:29 AM
Description: Rendering ingredient

java.lang.NullPointerException: Rendering ingredient
	at org.cyclops.cyclopscore.client.model.DynamicBaseModel.addColoredBakedQuad(DynamicBaseModel.java:145)
	at org.cyclops.fluidconverters.client.model.ModelFluidConverter.getGeneralQuads(ModelFluidConverter.java:85)
	at org.cyclops.cyclopscore.client.model.DynamicItemAndBlockModel.func_188616_a(DynamicItemAndBlockModel.java:50)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:122)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:106)
	at mezz.jei.render.GuiIngredientFast.renderItemAndEffectIntoGUI(GuiIngredientFast.java:139)
	at mezz.jei.render.GuiIngredientFast.renderItemAndEffectIntoGUI(GuiIngredientFast.java:112)
	at mezz.jei.render.GuiIngredientFastList.render(GuiIngredientFastList.java:169)
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:141)
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:174)
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:74)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_709_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:575)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:616)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:349)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1115)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.cyclops.cyclopscore.client.model.DynamicBaseModel.addColoredBakedQuad(DynamicBaseModel.java:145)
	at org.cyclops.fluidconverters.client.model.ModelFluidConverter.getGeneralQuads(ModelFluidConverter.java:85)
	at org.cyclops.cyclopscore.client.model.DynamicItemAndBlockModel.func_188616_a(DynamicItemAndBlockModel.java:50)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:122)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:106)

-- Ingredient being rendered --
Details:
	Ingredient Mod: FluidConverters
	Ingredient Info: 1xtile.blocks.fluidconverters.fluidconverter@0 fluidconverters:fluidconverter nbt:{fluidGroupRef:{fluidGroupId:"blood"}}
Stacktrace:
	at mezz.jei.render.GuiIngredientFast.createRenderIngredientException(GuiIngredientFast.java:399)
	at mezz.jei.render.GuiIngredientFast.renderItemAndEffectIntoGUI(GuiIngredientFast.java:114)
	at mezz.jei.render.GuiIngredientFastList.render(GuiIngredientFastList.java:169)
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:141)
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:174)
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:74)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_709_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:575)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:616)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:349)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1115)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (256, 191). Absolute: (512, 384)
	Screen size: Scaled: (512, 384). Absolute: (1024, 768). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Lothrazar'/67, l='MpServer', x=-601.83, y=4.00, z=-72.82]]
	Chunk stats: MultiplayerChunkCache: 600, 600
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-606,4,-83), Chunk: (at 2,0,13 in -38,-6; contains blocks -608,0,-96 to -593,255,-81), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Level time: 136645 game time, 1045 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 24 total; [EntityItem['item.item.immersiveengineering.material.hemp_fiber'/32, l='MpServer', x=-623.75, y=3.94, z=-58.60], EntityPig['Pig'/33, l='MpServer', x=-577.51, y=4.00, z=-108.50], EntityHorse['Horse'/34, l='MpServer', x=-545.81, y=4.00, z=-143.69], EntityPig['Pig'/35, l='MpServer', x=-546.39, y=4.00, z=-79.25], EntityItem['item.item.egg'/36, l='MpServer', x=-547.58, y=4.00, z=-50.30], EntityChicken['Chicken'/37, l='MpServer', x=-544.65, y=4.00, z=-39.19], EntityItem['item.item.egg'/38, l='MpServer', x=-547.01, y=4.00, z=-33.96], EntityHorse['Horse'/39, l='MpServer', x=-538.90, y=4.00, z=-87.92], EntityPig['Pig'/40, l='MpServer', x=-541.89, y=4.00, z=-89.47], EntityPig['Pig'/41, l='MpServer', x=-528.36, y=4.00, z=-64.78], EntityChicken['Chicken'/42, l='MpServer', x=-540.83, y=4.00, z=-42.92], EntityPig['Pig'/43, l='MpServer', x=-540.01, y=4.00, z=-19.79], EntityPig['Pig'/46, l='MpServer', x=-524.01, y=4.00, z=-98.58], EntityPig['Pig'/49, l='MpServer', x=-525.71, y=4.00, z=-61.62], EntityPlayerSP['Lothrazar'/67, l='MpServer', x=-601.83, y=4.00, z=-72.82], EntityPig['Pig'/20, l='MpServer', x=-667.66, y=4.00, z=-141.72], EntitySheep['Sheep'/21, l='MpServer', x=-663.81, y=4.00, z=-90.72], EntityChicken['Chicken'/23, l='MpServer', x=-644.81, y=4.00, z=-108.87], EntitySheep['Sheep'/24, l='MpServer', x=-640.53, y=4.00, z=-112.40], EntityCow['Cow'/25, l='MpServer', x=-651.77, y=4.00, z=-95.83], EntityPig['Pig'/26, l='MpServer', x=-649.34, y=4.00, z=-45.76], EntityPig['Pig'/28, l='MpServer', x=-638.62, y=4.00, z=-35.72], EntityCow['Cow'/30, l='MpServer', x=-620.80, y=4.00, z=-126.02], EntityItem['item.item.immersiveengineering.seed.hemp'/31, l='MpServer', x=-623.23, y=3.94, z=-58.84]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1020818952 bytes (973 MB) / 2540941312 bytes (2423 MB) up to 4277534720 bytes (4079 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=2 -XX:+AggressiveOpts
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2420 47 mods loaded, 47 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2420.jar) 
	UCHIJAAAA	forge{14.21.1.2420} [Minecraft Forge] (forge-1.12-14.21.1.2420.jar) 
	UCHIJAAAA	securitycraft{v1.8.2.3-hotfix} [SecurityCraft] ([1.12] SecurityCraft v1.8.2.3-hotfix.jar) 
	UCHIJAAAA	actuallyadditions{1.12-r117} [Actually Additions] (ActuallyAdditions-1.12-r117.jar) 
	UCHIJAAAA	bdlib{1.14.1.5} [BD Lib] (bdlib-1.14.1.5-mc1.12.jar) 
	UCHIJAAAA	biomesoplenty{7.0.0.2291} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2291-universal.jar) 
	UCHIJAAAA	chameleon{1.12-4.1.3} [Chameleon] (Chameleon-1.12-4.1.3.jar) 
	UCHIJAAAA	codechickenlib{3.1.1.288} [CodeChicken Lib] (CodeChickenLib-1.12-3.1.1.288-universal.jar) 
	UCHIJAAAA	redstoneflux{2.0.1} [Redstone Flux] (RedstoneFlux-1.12-2.0.1.2-universal.jar) 
	UCHIJAAAA	cofhcore{4.3.3} [CoFH Core] (CoFHCore-1.12-4.3.3.11-universal.jar) 
	UCHIJAAAA	cofhworld{1.0.0} [CoFH World] (CoFHWorld-1.12-1.0.0.6-universal.jar) 
	UCHIJAAAA	forgecreeperheal{1.3.0} [[Unofficial] Forge Creeper Heal] (creeperheal-1.12-1.3.1.jar) 
	UCHIJAAAA	jei{4.7.3.78} [Just Enough Items] (jei_1.12-4.7.3.78.jar) 
	UCHIJAAAA	cyclicmagic{1.7.1} [Cyclic] (Cyclic-1.12-1.7.2.jar) 
	UCHIJAAAA	cyclopscore{0.10.10} [Cyclops Core] (CyclopsCore-1.12-0.10.10.jar) 
	UCHIJAAAA	embers{0.221} [Embers] (embers-0.221.jar) 
	UCHIJAAAA	evilcraft{0.10.30} [EvilCraft] (EvilCraft-1.12-0.10.30.jar) 
	UCHIJAAAA	evilcraftcompat{1.0.0} [EvilCraft-Compat] (EvilCraft-1.12-0.10.30.jar) 
	UCHIJAAAA	fluidconverters{2.2.5} [FluidConverters] (FluidConverters-1.12-2.2.5.jar) 
	UCHIJAAAA	ic2{2.8.14-ex112} [IndustrialCraft 2] (industrialcraft-2-2.8.14-ex112.jar) 
	UCHIJAAAA	forestry{5.5.0.154} [Forestry] (forestry_1.12-5.5.0.154.jar) 
	UCHIJAAAA	forgelin{1.5.1} [Shadowfacts' Forgelin] (Forgelin-1.5.1.jar) 
	UCHIJAAAA	mantle{1.12-1.3.1.18} [Mantle] (Mantle-1.12-1.3.1.18.jar) 
	UCHIJAAAA	tconstruct{1.12-2.7.2.15} [Tinkers' Construct] (TConstruct-1.12-2.7.2.15.jar) 
	UCHIJAAAA	immersiveengineering{0.12-69} [Immersive Engineering] (ImmersiveEngineering-0.12-69.jar) 
	UCHIJAAAA	immersivepetroleum{1.1.2} [Immersive Petroleum] (immersivepetroleum-1.12-1.1.2.jar) 
	UCHIJAAAA	tesla{1.0.60} [TESLA] (Tesla-1.12-1.0.60.jar) 
	UCHIJAAAA	teslacorelib{1.12-1.0.5} [Tesla Core Lib] (tesla-core-lib-1.12-1.0.5.jar) 
	UCHIJAAAA	industrialforegoing{1.11.2-1.1} [Industrial Foregoing] (industrialforegoing-1.12-1.1-23.jar) 
	UCHIJAAAA	mob_grinding_utils{0.3.2} [mob_grinding_utils] (MobGrindingUtils-0.3.2.jar) 
	UCHIJAAAA	natura{1.12-4.3.0.10} [Natura] (Natura-1.12-4.3.0.10.jar) 
	UCHIJAAAA	samsocean{1.0.1} [Ocean Floor Classic] (OceanFloor-1.12-1.0.1.jar) 
	UCHIJAAAA	powerinventory{2.3.1} [Overpowered Inventory] (OverpoweredInventory-1.12-2.3.1.jar) 
	UCHIJAAAA	harvestcraft{1.12b} [Pam's HarvestCraft] (Pam's HarvestCraft 1.12b.jar) 
	UCHIJAAAA	pressure{1.3.1.1} [Pressure Pipes] (pressure-1.3.1.1-mc1.12.jar) 
	UCHIJAAAA	roots{0.025} [Roots 2] (roots-2-0.025.jar) 
	UCHIJAAAA	rustic{0.4.1} [Rustic] (rustic-0.4.1.jar) 
	UCHIJAAAA	similsaxtranstructors{1.12-1.0.21} [Similsax Transtructors] (SimilsaxTranstructors-1.12-1.0.22.jar) 
	UCHIJAAAA	storagenetwork{1.0.0} [Simple Storage Network] (SimpleStorageNetwork-1.12-1.0.13.jar) 
	UCHIJAAAA	storagedrawers{1.12-5.2.5} [Storage Drawers] (StorageDrawers-1.12-5.2.9.jar) 
	UCHIJAAAA	thermalfoundation{2.3.3} [Thermal Foundation] (ThermalFoundation-1.12-2.3.3.10-universal.jar) 
	UCHIJAAAA	thermalcultivation{0.1.0} [Thermal Cultivation] (ThermalCultivation-1.12-0.1.0.5-universal.jar) 
	UCHIJAAAA	thermaldynamics{2.3.3} [Thermal Dynamics] (ThermalDynamics-1.12-2.3.3.10-universal.jar) 
	UCHIJAAAA	thermalexpansion{5.3.3} [Thermal Expansion] (ThermalExpansion-1.12-5.3.3.15-universal.jar) 
	UCHIJAAAA	teslacoreregistries{1.12-1.0.5} [Tesla Core Registries] (tesla-core-lib-1.12-1.0.5.jar) 
	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.5.1.jar)
  
IELoadingPlugin (ImmersiveEngineering-0.12-69.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 381.65' Renderer: 'GeForce GT 730/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	List of loaded APIs: 
		* actuallyadditionsapi (33) from ActuallyAdditions-1.12-r117.jar
		* cofhapi (2.0.0) from CoFHCore-1.12-4.3.3.11-universal.jar
		* cofhapi|block (2.0.0) from CoFHCore-1.12-4.3.3.11-universal.jar
		* cofhapi|core (2.0.0) from CoFHCore-1.12-4.3.3.11-universal.jar
		* cofhapi|item (2.0.0) from CoFHCore-1.12-4.3.3.11-universal.jar
		* cofhapi|tileentity (2.0.0) from CoFHCore-1.12-4.3.3.11-universal.jar
		* cofhapi|util (2.0.0) from CoFHCore-1.12-4.3.3.11-universal.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.12-5.5.0.154.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.12-5.5.0.154.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.12-5.5.0.154.jar
		* ForestryAPI|climate (2.1.0) from forestry_1.12-5.5.0.154.jar
		* ForestryAPI|core (5.1.0) from forestry_1.12-5.5.0.154.jar
		* ForestryAPI|farming (2.2.0) from forestry_1.12-5.5.0.154.jar
		* ForestryAPI|food (1.1.0) from forestry_1.12-5.5.0.154.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.12-5.5.0.154.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.12-5.5.0.154.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.12-5.5.0.154.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.12-5.5.0.154.jar
		* ForestryAPI|lepidopterology (1.4.0) from forestry_1.12-5.5.0.154.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.12-5.5.0.154.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.12-5.5.0.154.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.12-5.5.0.154.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.12-5.5.0.154.jar
		* ForestryAPI|world (2.1.0) from forestry_1.12-5.5.0.154.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.12-69.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.12-69.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12-4.7.3.78.jar
		* pressureAPI (1.3.1.1) from pressure-1.3.1.1-mc1.12.jar
		* SecurityCraftAPI (1.2.1) from [1.12] SecurityCraft v1.8.2.3-hotfix.jar
		* StorageDrawersAPI (2.1.0) from StorageDrawers-1.12-5.2.9.jar
		* StorageDrawersAPI|event (2.1.0) from StorageDrawers-1.12-5.2.9.jar
		* StorageDrawersAPI|registry (2.1.0) from StorageDrawers-1.12-5.2.9.jar
		* StorageDrawersAPI|render (2.1.0) from StorageDrawers-1.12-5.2.9.jar
		* StorageDrawersAPI|storage (2.1.0) from StorageDrawers-1.12-5.2.9.jar
		* StorageDrawersAPI|storage-attribute (2.1.0) from StorageDrawers-1.12-5.2.9.jar
	Launched Version: forge-14.21.1.2420
	LWJGL: 2.9.4
	OpenGL: GeForce GT 730/PCIe/SSE2 GL version 4.5.0 NVIDIA 381.65, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz

**Comment by rubensworks** [comment]
Hmm, I thought I fixed something like this just recently.

**Comment by rubensworks** [comment]
Ah, you're not using the latest version. This was fixed in 2.2.6.
